server:
  port: 8086


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dilect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


